//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BreakfastCards1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ActualQuantity
    {
        public string ID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string GroupName { get; set; }
        public string Cards { get; set; }
        public Nullable<int> ActualQuantity { get; set; }
    }
}
